[package]
name = "aoc"
version = "0.1.0"
authors = ["Kevin Caffrey <kcaffrey@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
aoc-runner = "0.2"
aoc-runner-derive = "0.2"
regex = "1"
rayon = "1.0"
lazy_static = "1.2.0"
num-traits = "0.2"
